### ISSUE TITLE
Use a pre-compiled release of `ldproxy` instead of building from source

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/xtensa-toolchain#3]

**Comment by SergioGasquez** [comment]
If I am not miss understanding the issue, this is already done in the updated installer with https://github.com/esp-rs/rust-build/blob/main/install-rust-toolchain.sh#L330-L333

**Comment by jessebraham** [comment]
Oh perfect, didn't realize it had been updated already. Thanks for pointing that out!
