### ISSUE TITLE
Installation script is downloaded in the current directory instead of in $HOME

### ISSUE THREAD

**Issue by ivmarkov** [esp-rs/xtensa-toolchain#8]
[Here](https://github.com/esp-rs/xtensa-toolchain/blob/main/install.sh#L32).

... and since the current directory is the crate which is being build, the above blocks publishing the crate on crates.io, as `cargo publish` complains that there is a dirty (not git-ignored and not committed) file in the repo.

The above ATM prohibits me from releasing a new version of `esp-idf-hal`.
I'll workaround the issue  by `.gitignore`-ing the installation script, but it would be good if the action is not polluting the crate directory nevertheless. :)

**Comment by jessebraham** [comment]
Ahh, sorry about that. I think between this and #7 that's probably enough to warrant a new minor version of the action, so I'll try to get that done as soon as possible.

**Comment by jessebraham** [comment]
This should be resolved by [043a04e](https://github.com/esp-rs/xtensa-toolchain/commit/043a04ee6ae037180cc755e07abc8b4a1e92f91a). I'll leave this issue open until I create a new version of the action.

**Comment by jessebraham** [comment]
I've created `v1.3` of this action, so this should be resolved.
